import SyntaxHighlighter from 'react-syntax-highlighter';
import { anOldHope, stackoverflowDark } from 'react-syntax-highlighter/dist/esm/styles/hljs';

const Components = () => {
  const code_quickly = `
  <ul class="nav nav-pills nav-fill gap-2 p-1 small bg-primary rounded-5 shadow-sm" id="pillNav2" role="tablist" style="--bs-nav-link-color: var(--bs-white); --bs-nav-pills-link-active-color: var(--bs-primary); --bs-nav-pills-link-active-bg: var(--bs-white);">
    <li class="nav-item" role="presentation">
      <button class="nav-link active rounded-5" id="home-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="true">Home</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link rounded-5" id="profile-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="false">Profile</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link rounded-5" id="contact-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="false">Contact</button>
    </li>
  </ul>
  `
  const code_create = `
  @import "bootstrap/scss/bootstrap";

  $utilities: map-merge(
    $utilities,
    (
      "cursor": (
        property: cursor,
        class: cursor,
        responsive: true,
        values: auto pointer grab,
      )
    )
  );
  `
  return (
    <section className="container mx-auto mb-12 pb-12">
      <div className="w-[780px] mb-12">
        <div className="flex items-center gap-2 mb-4">
          <div className="bg-red-800/15 p-4 inline-block rounded-2xl">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-menu-button-wide-fill w-10 h-10 text-red-500" viewBox="0 0 16 16">
              <path d="M1.5 0A1.5 1.5 0 0 0 0 1.5v2A1.5 1.5 0 0 0 1.5 5h13A1.5 1.5 0 0 0 16 3.5v-2A1.5 1.5 0 0 0 14.5 0zm1 2h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1 0-1m9.927.427A.25.25 0 0 1 12.604 2h.792a.25.25 0 0 1 .177.427l-.396.396a.25.25 0 0 1-.354 0zM0 8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm1 3v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2zm14-1V8a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2zM2 8.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5"/>
            </svg>
          </div>
          <div className="text-4xl font-extralight w-8 h-8 flex justify-center items-center">
            +
          </div>
          <div className="bg-emerald-800/15 p-4 inline-block rounded-2xl">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-braces-asterisk w-10 h-10 text-emerald-300" viewBox="0 0 16 16">
              <path fillRule="evenodd" d="M1.114 8.063V7.9c1.005-.102 1.497-.615 1.497-1.6V4.503c0-1.094.39-1.538 1.354-1.538h.273V2h-.376C2.25 2 1.49 2.759 1.49 4.352v1.524c0 1.094-.376 1.456-1.49 1.456v1.299c1.114 0 1.49.362 1.49 1.456v1.524c0 1.593.759 2.352 2.372 2.352h.376v-.964h-.273c-.964 0-1.354-.444-1.354-1.538V9.663c0-.984-.492-1.497-1.497-1.6M14.886 7.9v.164c-1.005.103-1.497.616-1.497 1.6v1.798c0 1.094-.39 1.538-1.354 1.538h-.273v.964h.376c1.613 0 2.372-.759 2.372-2.352v-1.524c0-1.094.376-1.456 1.49-1.456v-1.3c-1.114 0-1.49-.362-1.49-1.456V4.352C14.51 2.759 13.75 2 12.138 2h-.376v.964h.273c.964 0 1.354.444 1.354 1.538V6.3c0 .984.492 1.497 1.497 1.6M7.5 11.5V9.207l-1.621 1.621-.707-.707L6.792 8.5H4.5v-1h2.293L5.172 5.879l.707-.707L7.5 6.792V4.5h1v2.293l1.621-1.621.707.707L9.208 7.5H11.5v1H9.207l1.621 1.621-.707.707L8.5 9.208V11.5z"/>
            </svg>
          </div>
        </div>
        <h2 className="text-5xl font-bold mb-4">Components, meet the Utility API</h2>
        <p className="text-xl mb-4">New in Bootstrap 5, our utilities are now generated by our <a href="#" className="text-blue-400 underline hover:brightness-125">Utility API</a>. We built it as a feature-packed Sass map that can be quickly and easily customized. It's never been easier to add, remove, or modify any utility classes. Make utilities responsive, add pseudo-class variants, and give them custom names.</p>
      </div>

      <div className="grid grid-cols-2 gap-12">
        <div className="mb-4">
          <h3 className="text-3xl mb-2 font-semibold">Quickly customize components</h3>
          <p className="mb-4">Apply any of our included utility classes to our components to customize their appearance, like the navigation example below. There are hundreds of classes available—from <a href="#" className="text-blue-400 underline hover:brightness-125">positioning</a> and <a href="#" className="text-blue-400 underline hover:brightness-125">sizing</a> to <a href="#" className="text-blue-400 underline hover:brightness-125">colors</a> and <a href="#" className="text-blue-400 underline hover:brightness-125">effects</a>. Mix them with CSS variable overrides for even more control.</p>

          {/* <div className="text-sm rounded-md mb-4 overflow-hidden border border-gray-600">
            <SyntaxHighlighter language='htmlbars' style={stackoverflowDark}>
            {code_quickly}
            </SyntaxHighlighter>
          </div> */}
          {/* <div className="text-sm rounded-md mb-4 overflow-hidden border border-gray-600">
            <SyntaxHighlighter language='htmlbars' style={stackoverflowDark}>
            {code_quickly}
            </SyntaxHighlighter>
          </div> */}

          <div className="group font-semibold text-blue-400 inline-flex items-center">
            <div className="group-hover:brightness-125 group-hover:cursor-pointer underline underline-offset-4">
              Explore customized components
            </div>
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-arrow-right inline-block w-5 h-5 ml-1 group-hover:translate-x-1 transition-transform" viewBox="0 0 16 16">
              <path fillRule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"/>
            </svg>
          </div>
        </div>
        <div className="mb-4">
          <h3 className="text-3xl mb-2 font-semibold">Create and extend utilities</h3>
          <p className="mb-4">Use Bootstrap's utility API to modify any of our included utilities or create your own custom utilities for any project. Import Bootstrap first, then use Sass map functions to modify, add, or remove utilities.</p>

          <div className="text-sm rounded-md mb-4 overflow-hidden border border-gray-600">
            <SyntaxHighlighter language='scss' style={anOldHope}>
            {code_create}
            </SyntaxHighlighter>
          </div>

          <div className="group font-semibold text-blue-400 inline-flex items-center">
            <div className="group-hover:brightness-125 group-hover:cursor-pointer underline underline-offset-4">
              Explore the utility API
            </div>
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" className="bi bi-arrow-right inline-block w-5 h-5 ml-1 group-hover:translate-x-1 transition-transform" viewBox="0 0 16 16">
              <path fillRule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"/>
            </svg>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Components